### ISSUE TITLE
Please add Slope Physics / Collision

### ISSUE THREAD

**Issue by Thundros** [davidinfante/First-Person-Shooter-JS#1]
Hi, I came across your demo while searching for three.js stuff & I must say. For not very much there, it is SO awesome! I just had a quick question though. Could you add slope physics / collision so the player can slide down steep slopes and walk on non-steep slopes based on the angle of the slope? That would be GREAT!

Keep up the good work!

Thundros

**Comment by davidinfante** [comment]
> Hi, I came across your demo while searching for three.js stuff & I must say. For not very much there, it is SO awesome! I just had a quick question though. Could you add slope physics / collision so the player can slide down steep slopes and walk on non-steep slopes based on the angle of the slope? That would be GREAT!
> 
> Keep up the good work!
> 
> Thundros

Hi @Thundros, sorry for the late reply, your comment was totally unexpected but we are really happy that someone liked one of our university projects! To clarify a little, we are still pretty noob with javascript, three.js and physijs so this whole thing is kind of improvised.

To answer your question, we already had those physics added to the player some commits ago (this is the link to the commit where we had those physics implemented: (copy and paste it if it doesn't redirect you as expected) [https://github.com/davidinfante/First-Person-Shooter-JS/commit/2724537c6d0793956fb592f0f75f8b13f2ae3c42](url)) but we decided to remove them because the interactions that it had with the fences or when landing a jump made the "player" (we named it "avatar") in some circumstances so unstable that it could fell backwards to the ground making it impossible to play and having to restart the game.

If you are still interested in having those physics is as simple as changing the creation of:
`this.avatar = new THREE.Mesh (new THREE.BoxGeometry (5, 5, 5), mat);` in the constructor of the avatar.js file to:
`this.avatar = new Physijs.BoxMesh (new THREE.BoxGeometry (5, 5, 5), mat , 1000);`
(1000 being the mass of the avatar so you can change it to whatever you want).
However, if you implement these physics you have to change the way the avatar jumps and moves too. Check TheScene.js and avatar.js files in the commit previously linked because they had these changes to the movement and jump implemented.

With that, the avatar will slide down steep slopes with 0 mass; remember that the mass you give to the avatar will affect the speed it slides and so on.

I hope this really helped you and if you have some other questions feel free to ask them!

David

**Comment by Thundros** [comment]
Hi David! Thanks for taking your time to comment. I really appreciate it! This will work with Terrains, correct? If not, could you possibly implement a simple terrain steep / non-steep slope sliding / walking example? I know it may sound a bit too much to ask & feel free not to answer this at all if you don't wish to, but I think it's about time we took Three.js to a new level. I really look forward to your answer if you wish to answer this. Thank you SO much David. You have NO idea HOW much this means to me! Have a GREAT evening & a good day tomorrow! :) And Happy Memorial day / weekend, btw!

**Comment by davidinfante** [comment]
Hi again Thundros, I've been quite busy but I've made you a simple terrain steep / non-steep slope sliding / walking example based on the complete project with Physijs and THREE.js, you can download it here and try it out: [Physijs example](https://github.com/davidinfante/Examples).

If you have any questions please leave them here.

David

**Comment by Thundros** [comment]
Thanks ALOT, David! I really appreciate this! I have a few questions. One being, where can I change the steep slope value so that I can change the angle at which steep slope activates? So like say for instance I ONLY wanted to slide down angles which are greater than or equal to 65 degrees of rotation on the X-Axis, I would be able to put 90 & the character would NOT be able to climb up a steep, 90-degree wall on the terrain. I need to be able to walk on & NOT slide on slopes that are LESS than 65.0 degrees rotation on the X-Axis. I need to apply sliding collision to angles that are greater than or equal to 65.0 degrees on the X-rotation Axis. So basically like this 👍 

This is a video someone uploaded a long time ago playing World of Warcraft showing the Terrain example : 

https://youtu.be/c3gkp1iYTdU?t=53

This is a video I just uploaded of me playing NeverWinter showing the Terrain example : 

https://www.youtube.com/watch?v=TrtgWQduMvQ&feature=youtu.be

As you can see, he / I slide(s) down the STEEP part of the Terrain & can walk on the NOT steep part of the Terrain.

It would be GREAT if you could make this example work simply like this.

Thank you SO much for ALL of your help! You have NO idea how much this means to me!

Friends always, 

Thundros

**Comment by davidinfante** [comment]
Hi Thundros, I've tried what you asked but it's not working on this example, I'll try to explain you why.

In the example I uploaded I used Physijs, a library that provides you with gravity and other sort of physics. I created a 65 degrees slope but with the movement I implemented, the avatar could go through the slope a little bit, so the answer of Physijs is to throw away the avatar as it is not supposed to be in the slope.

I'm afraid that in the video you uploaded and in the other one the physics engine just works that way, meaning that there is no "steep slope value you can change" as that is previously implemented in the engine.
It's like the character collides with the slope not because the game programmers designed it that way, I believe it's just because the engine works that way.

I'm sorry I couldn't help you with this, my Physijs knowledge it's not much at all.

David

**Comment by Thundros** [comment]
I just need to be able to slide along Terrain if it is too steep. Whether
it be with or without the PhysiJS.
